- name: install docker and config
  hosts: all
  gather_facts: no
  become: true
  vars:
    docker_compose_version: 1.29.2  # Specify the desired Docker Compose version
  tasks:
    - name: update all pkgs
      yum:
        name: "*"
        state: latest

    - name: Remove docker if installed from CentOS repo
      yum:
        name: "{{ item }}"
        state: removed
      loop:
        - docker
        - docker-client
        - docker-client-latest
        - docker-common
        - docker-latest
        - docker-latest-logrotate
        - docker-logrotate
        - docker-engine

    - name: Install yum utils
      yum: 
        name: yum-utils
        state: latest

    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo

    - name: Install Docker
      package:
        name: docker-ce
        state: latest
  
    - name: Install pip
      package:
        name: python3-pip
        state: present

    - name: Upgrade pip
      pip:
        name: pip
        state: latest

    - name: Install docker-compose
      pip:
        name: docker-compose
        version: "{{ docker_compose_version }}"

    - name: Install docker sdk
      pip:
        name: docker

    - name: Add user ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Download Docker Compose binary
      get_url:
        url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64"
        dest: /usr/local/bin/docker-compose
        mode: 'u=rwx,g=rx,o=rx'

    - name: Set execute permissions on Docker Compose binary
      file:
        path: /usr/local/bin/docker-compose
        mode: 'u=rwx,g=rx,o=rx'


    - name: Start todo app 
      docker_compose:
        project_src: "{{ playbook_dir }}"
        files:
          - docker-compose.yml
        build: yes
        state: present