- name: bridge networks config
  hosts: all
  become: true
  gather_facts: no
  tasks:
    - name: Create docker networks bridge
      docker_network:
        name: all2
        driver: bridge

- name: postgre database config
  hosts: all
  become: true
  gather_facts: no
  tasks:
    - name: Launch postgresql docker container
      docker_container:
        name: postgres_container
        image: postgres:latest
        state: started
        restart_policy: always
        ports: 
          - "5432:5432"
        env:
          POSTGRES_USER: "postgres"
          POSTGRES_PASSWORD: "admin"
        volumes:
          - /db-data:/var/lib/postgresql/data
          - /home/ec2-user/todo/todoserver/src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql:rw
        networks:
          - name: all2
      register: container_info

    - name: print the container info
      debug:
        var: container_info
    
    - name: Wait for TCP port to be available
      wait_for:
        host: "172.31.4.30"
        port: "5432"
        delay: 10
        timeout: 300

- name: todo Server configuration
  hosts: all
  become: true
  gather_facts: no
  vars: 
    container_path: /home/ec2-user/todo/todoserver
    container_name: todo_server
    image_name: todo_server:latest
  tasks:
    - name: build todoserver container image
      docker_image:
        name: "{{ image_name }}"
        build:
          path: "{{ container_path }}"
        source: build
        state: present

    - name: Launch todoserver docker container
      docker_container:
        name: "{{ container_name }}"
        image: "{{ image_name }}"
        state: started
        ports:
          - "8000:8000"
        env: 
          SPRING_DATASOURCE_URL: "jdbc:postgresql://172.31.4.30:5432/todo_db"

        networks:
          - name: all2
      when: container_info is succeeded
