- name: bridge networks config
  hosts: all
  become: true
  gather_facts: no
  tasks:
    - name: Create docker networks bridge
      docker_network:
        name: all2
        driver: bridge

- name: Launch pgadmin_container
  hosts: all
  become: true
  gather_facts: no

  tasks:
    - name: Launch pgadmin docker container
      docker_container:
        name: pgadmin_container
        image: dpage/pgadmin4
        state: started
        ports: 
        - "5050:80"
        env:
          PGADMIN_DEFAULT_EMAIL: 'pgadmin4@pgadmin.org'
          PGADMIN_DEFAULT_PASSWORD: 'admin'
          PGADMIN_CONFIG_SERVER_MODE: 'False'
          PGADMIN_LISTEN_ADDRESS: '0.0.0.0'
          PGADMIN_LISTEN_PORT: '80'
        volumes: 
          - pgadmin:/root/.pgadmin
        networks:
          - name: all2